[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "music_sync"
authors = [{"name" = "Lucas Chizzali"}]
description = "Syncing Apple Music Library to Spotify"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
    "auto_mix_prep==0.2.0",
    "click~=8.1.7",
    "flask~=2.2.5",
    "loguru~=0.7.3",
    "mypy",
    "notebook",
    "numpy~=1.26.3",
    "pandas~=2.1.4",
    "pandas-stubs==2.3.3.260113",
    "pre-commit",
    "pydantic~=2.11.2",
    "pytest",
    "rapidfuzz~=3.13.0",
    "requests~=2.31.0",
    "ruff",
    "spotipy==2.23.0",
    "tqdm>=4.67.1",
    "werkzeug~=2.2.3",
]

[tool.setuptools.dynamic]
version = {attr = "music_sync.__version__"}

[tool.ruff]
extend-include = ["*.ipynb"]
target-version = "py310"
line-length = 88

[tool.ruff.lint]
extend-select = [
    "W605",   # pycodestyle: invalid-escape-sequence
    "S102",   # flake8-bandit: exec-builtin
    "INP",    # flake8-no-pep420
    "PYI",    # flake8-pyi
    "PT",     # flake8-pytest-style
    "PGH",    # pygrep-hooks
    "PL",     # Pylint
    "NPY",    # NumPy-specific rules
    "RUF",    # Ruff-specific rules
]
ignore = [
    "NPY002", # numpy-legacy-random
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["INP001"]
"[!t][!e][!s][!t][!s]*/**" = ["PT"]
